# Generated by Django 4.2.7 on 2023-11-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "espécie",
                    models.CharField(
                        choices=[
                            ("Cachorro", "Cachorro"),
                            ("Gato", "Gato"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("idade", models.IntegerField()),
                (
                    "raça",
                    models.CharField(
                        choices=[
                            ("Akita", "Akita"),
                            ("Angorá Turco", "Angorá Turco"),
                            ("Bobtail Americano", "Bobtail Americano"),
                            ("Chihuahua", "Chihuahua"),
                            ("Gato Europeu", "Gato Europeu"),
                            ("Maltês", "Maltês"),
                            ("Mau Egipcioa", "Mau Egipcio"),
                            ("Poodle", "Poodle"),
                            ("Siamês", "Siamês"),
                            ("Siberiano", "Siberiano"),
                            ("Shih Tzu", "Shih Tzu"),
                            ("Yorkshire Terrie", "Yorkshire Terrie"),
                            ("Outro", "Outro"),
                        ],
                        max_length=100,
                    ),
                ),
                ("histórico_de_saúde", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
            ],
            options={
                "verbose_name": "Formulário de Cadastro de Animal",
                "verbose_name_plural": "Formulários de Cadastros de Animais",
                "ordering": ["idade"],
            },
        ),
    ]
