# Generated by Django 4.2.7 on 2023-12-02 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=77)),
                ("CPF", models.CharField(max_length=11)),
                ("data_nascimento", models.DateField(help_text="dd/mm/aaaa")),
                (
                    "sexo",
                    models.CharField(
                        choices=[("f", "Feminino"), ("m", "Masculino")], max_length=100
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[("c", "Cuidador"), ("", "Voluntário")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contato",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                ("endereco", models.CharField(max_length=255)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
            ],
            options={
                "verbose_name": "Formulário de Cadastro do Contribuinte",
                "verbose_name_plural": "Formulários de Cadastros dos Contribuintes",
                "ordering": ["CPF"],
            },
        ),
    ]
