# Generated by Django 4.2.7 on 2023-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrousuario",
            name="funcao",
            field=models.CharField(
                choices=[("c", "Cuidador"), ("", "Voluntário")], max_length=100
            ),
        ),
    ]
