# Generated by Django 4.2.7 on 2023-11-24 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_alter_cadastrousuario_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cadastrousuario",
            old_name="imagens",
            new_name="foto",
        ),
        migrations.RemoveField(
            model_name="cadastrousuario",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="cadastrousuario",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="cadastrousuario",
            name="numero",
        ),
        migrations.AlterField(
            model_name="cadastrousuario",
            name="contato",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
