# Generated by Django 4.2.7 on 2023-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_alter_cadastrousuario_funcao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrousuario",
            name="funcao",
            field=models.CharField(
                choices=[("c", "Cuidador"), ("", "Voluntário")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="cadastrousuario",
            name="sexo",
            field=models.CharField(
                choices=[("f", "Feminino"), ("m", "Masculino")], max_length=10
            ),
        ),
    ]
