# Generated by Django 4.2.7 on 2023-11-25 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_rename_imagens_cadastrousuario_foto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrousuario",
            name="contato",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
