# Generated by Django 4.2.7 on 2023-12-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_alter_cadastrousuario_funcao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrousuario",
            name="funcao",
            field=models.CharField(
                choices=[("Cuidador", "Cuidador"), ("Voluntário", "Voluntário")],
                max_length=10,
            ),
        ),
    ]
