# Generated by Django 4.2.7 on 2023-12-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0008_alter_cadastrousuario_funcao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cadastrousuario",
            old_name="funcao",
            new_name="função",
        ),
    ]
