# Generated by Django 4.2.7 on 2023-12-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0009_rename_funcao_cadastrousuario_função"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastrousuario",
            name="função",
        ),
        migrations.AddField(
            model_name="cadastrousuario",
            name="funcao",
            field=models.CharField(
                choices=[("c", "Cuidador"), ("v", "Voluntário")],
                default="",
                max_length=10,
            ),
        ),
    ]
