# Generated by Django 4.2.7 on 2023-12-10 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animais", "0004_alter_cadastroanimal_raça"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaleConosco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mensagem", models.TextField()),
            ],
            options={
                "verbose_name": "Formulário de contato",
                "verbose_name_plural": "Formulários de contato",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PedidoAdocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("endereço", models.CharField(max_length=120)),
                (
                    "contato",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "solicitação",
                    models.CharField(
                        choices=[
                            ("Aceito", "Aceito"),
                            ("Recusado", "Recusado"),
                            ("Em análise", "Em análise"),
                        ],
                        max_length=30,
                    ),
                ),
                ("cuidados_com_animal", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="animais.cadastroanimal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulário de Adoção de Animal",
                "verbose_name_plural": "Formulários de Adoções de Animais",
                "ordering": ["solicitação"],
            },
        ),
    ]
