# Generated by Django 4.2.7 on 2023-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrigo_animais", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cadastro",
            options={
                "ordering": ["idade"],
                "verbose_name": "Formulário de Cadastro de Animal",
                "verbose_name_plural": "Formulários de Cadastros de Animais",
            },
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="histórico_de_saúde",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="imagens",
            field=models.FileField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="raça",
            field=models.CharField(
                choices=[
                    ("Cachorro", "Cachorro"),
                    ("Gato", "Gato"),
                    ("Outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
    ]
