# Generated by Django 4.2.7 on 2023-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrigo_animais", "0002_alter_cadastro_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="espécie",
            field=models.CharField(
                choices=[
                    ("Cachorro", "Cachorro"),
                    ("Gato", "Gato"),
                    ("Outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="raça",
            field=models.CharField(max_length=100),
        ),
    ]
