# Generated by Django 4.2.7 on 2023-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrigo_animais", "0002_alter_pedidoadocao_solicitação"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidoadocao",
            name="solicitação",
            field=models.CharField(
                choices=[
                    ("Aceito", "Aceito"),
                    ("Recusado", "Recusado"),
                    ("Em análise", "Em análise"),
                ],
                max_length=30,
            ),
        ),
    ]
