# Generated by Django 4.2.7 on 2023-11-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrigo_animais", "0004_alter_cadastro_raça"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="imagens",
            field=models.ImageField(blank=True, null=True, upload_to="uploads"),
        ),
    ]
