# Generated by Django 4.2.7 on 2023-11-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrigo_animais", "0005_alter_cadastro_imagens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="imagens",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
