# Generated by Django 4.2.7 on 2023-11-24 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrigo_animais", "0006_alter_cadastro_imagens"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoAdocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("endereço", models.CharField(max_length=120)),
                (
                    "contato",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "solicitação",
                    models.CharField(
                        choices=[
                            ("Aceito", "Aceito"),
                            ("Recusado", "Recusado"),
                            ("Em análise", "Em análise"),
                        ],
                        max_length=30,
                    ),
                ),
                ("cuidados_com_animal", models.TextField()),
            ],
            options={
                "verbose_name": "Formulário de Adoção de Animal",
                "verbose_name_plural": "Formulários de Adoções de Animais",
                "ordering": ["solicitação"],
            },
        ),
        migrations.DeleteModel(
            name="Cadastro",
        ),
    ]
