# Generated by Django 4.2.7 on 2023-11-25 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrigo_animais", "0007_pedidoadocao_delete_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidoadocao",
            name="contato",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
